# Generated by Django 5.0.6 on 2024-05-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='watch_list',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='stocks',
            field=models.ManyToManyField(to='accounts.stock', verbose_name='Stocks'),
        ),
    ]
