# Generated by Django 5.0.6 on 2024-05-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_stock_watch_list_watchlist_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='type',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
